console.log('Welcome to Java Script Data Types Conversion.');
let num = "2024";
console.log(num);
console.log(typeof num);
let num1 = Number(num);
let num2 = parseInt(num);
let num3 = +num;
let num4 = Number("");
let num5 = Number(true);
let num6 = Number(false);
console.log(num1);
console.log(typeof num1);
console.log(num2);
console.log(typeof num2);
console.log(num3);
console.log(typeof num3);
console.log(num4);
console.log(typeof num4);
console.log(num5);
console.log(typeof num5);
console.log(num6);
console.log(typeof num6);